# Generated by Django 2.2.13 on 2020-07-22 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='昵称', max_length=255, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=18, verbose_name='用户年龄')),
                ('gender', models.CharField(default='男', max_length=2, verbose_name='性别')),
                ('telephone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改信息时间')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.jpg', upload_to='avatar/', verbose_name='用户头像')),
                ('sign', models.TextField(blank=True, max_length=500)),
                ('qq', models.CharField(blank=True, max_length=12, verbose_name='qq')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='github')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='个人网站')),
                ('is_display', models.BooleanField(default=False, verbose_name='是否展示个人信息')),
                ('occupation', models.CharField(default='个人开发者', max_length=15, verbose_name='身份')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户基本信息',
                'verbose_name_plural': '用户基本信息',
            },
        ),
    ]
